version: '3.8'
services:
  web:
    build:
      context: .
      target: dev # Use the development build stage
    image: web-client
    container_name: web-client
    expose:
      - 4200
    command: ["npm", "start"]
    ports:
      - 4200:4200
    volumes:
      - .:/app
    networks:
      - web_proxynet

networks:
  web_proxynet:
    external:
      name: shared_network