version: '3.8'
services:
  web:
    build: .
    image: frontend
    container_name: frontend
    ports:
      - 4200:4200
    volumes:
      - .:/app
    networks:
      - web_proxynet

networks:
  web_proxynet:
    external:
      name: shared_network